import {
  Archive,
  ArchiveRestore,
  ArrowDownLeft,
  ArrowLeftRight,
  ArrowUpRight,
  Baby,
  Banknote,
  Beer,
  Bike,
  Bitcoin,
  Book,
  Briefcase,
  Building2,
  Bus,
  Camera,
  Car,
  Cat,
  ChartCandlestick,
  ChartLine,
  ChartPie,
  Check,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleHelp,
  CirclePlus,
  Coffee,
  Coins,
  CreditCard,
  Dog,
  Droplets,
  Dumbbell,
  Film,
  Filter,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  HandCoins,
  Headphones,
  Heart,
  HeartPulse,
  House,
  type IconNode,
  Landmark,
  Laptop,
  List,
  LogOut,
  Music,
  Package,
  Pencil,
  Percent,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plus,
  ReceiptText,
  Repeat,
  Sandwich,
  Scissors,
  Settings,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Store,
  Sun,
  Tag,
  Train,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Tv,
  Undo2,
  User,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  X,
  Zap,
} from 'lucide';

/**
 * Icons a category may use. The database stores only the key; the frontend
 * resolves it here. Keys outside this list render the fallback icon.
 */
export const CATEGORY_ICONS: Record<string, IconNode> = {
  'shopping-cart': ShoppingCart,
  utensils: Utensils,
  house: House,
  bus: Bus,
  car: Car,
  'heart-pulse': HeartPulse,
  'shopping-bag': ShoppingBag,
  film: Film,
  plane: Plane,
  repeat: Repeat,
  briefcase: Briefcase,
  sandwich: Sandwich,
  gift: Gift,
  percent: Percent,
  'trending-up': TrendingUp,
  'circle-plus': CirclePlus,
  coffee: Coffee,
  pizza: Pizza,
  beer: Beer,
  fuel: Fuel,
  train: Train,
  bike: Bike,
  wifi: Wifi,
  smartphone: Smartphone,
  laptop: Laptop,
  tv: Tv,
  'gamepad-2': Gamepad2,
  music: Music,
  headphones: Headphones,
  camera: Camera,
  book: Book,
  'graduation-cap': GraduationCap,
  baby: Baby,
  dog: Dog,
  cat: Cat,
  dumbbell: Dumbbell,
  shirt: Shirt,
  scissors: Scissors,
  stethoscope: Stethoscope,
  pill: Pill,
  droplets: Droplets,
  zap: Zap,
  wrench: Wrench,
  hammer: Hammer,
  'building-2': Building2,
  store: Store,
  package: Package,
  sun: Sun,
  star: Star,
  heart: Heart,
  sparkles: Sparkles,
  trophy: Trophy,
  banknote: Banknote,
  coins: Coins,
  'hand-coins': HandCoins,
  'credit-card': CreditCard,
  landmark: Landmark,
  'piggy-bank': PiggyBank,
  sprout: Sprout,
  bitcoin: Bitcoin,
  'chart-line': ChartLine,
  tag: Tag,
};

export const CATEGORY_ICON_KEYS = Object.keys(CATEGORY_ICONS);

/** Icons used by the interface itself (navigation, actions, kinds). */
export const UI_ICONS: Record<string, IconNode> = {
  house: House,
  list: List,
  plus: Plus,
  'chart-pie': ChartPie,
  settings: Settings,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'arrow-left-right': ArrowLeftRight,
  'arrow-down-left': ArrowDownLeft,
  'arrow-up-right': ArrowUpRight,
  'chart-candlestick': ChartCandlestick,
  'undo-2': Undo2,
  'piggy-bank': PiggyBank,
  wallet: Wallet,
  'receipt-text': ReceiptText,
  pencil: Pencil,
  'trash-2': Trash2,
  archive: Archive,
  'archive-restore': ArchiveRestore,
  check: Check,
  x: X,
  filter: Filter,
  'log-out': LogOut,
  user: User,
  'triangle-alert': TriangleAlert,
  circle: Circle,
  'circle-help': CircleHelp,
};

export const FALLBACK_ICON: IconNode = CircleHelp;

export function resolveIcon(name: string): IconNode {
  return CATEGORY_ICONS[name] ?? UI_ICONS[name] ?? FALLBACK_ICON;
}

/** Inline SVG markup for an icon node; the source is this module's table. */
export function iconSvg(node: IconNode, size: number, strokeWidth = 2): string {
  const children = node
    .map(([tag, attrs]) => {
      const attributes = Object.entries(attrs)
        .map(([key, value]) => `${key}="${value}"`)
        .join(' ');
      return `<${tag} ${attributes}/>`;
    })
    .join('');

  return (
    `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 24 24" ` +
    `fill="none" stroke="currentColor" stroke-width="${strokeWidth}" stroke-linecap="round" ` +
    `stroke-linejoin="round" aria-hidden="true">${children}</svg>`
  );
}
